/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as TableHistoryRouteImport } from './routes/table-history'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrintersRouteImport } from './routes/printers'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as CustomerTablesRouteImport } from './routes/customer-tables'
import { Route as CouriersRouteImport } from './routes/couriers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as TableTableIdRouteImport } from './routes/table.$tableId'
import { Route as PosOrdersRouteImport } from './routes/pos/orders'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const TableHistoryRoute = TableHistoryRouteImport.update({
  id: '/table-history',
  path: '/table-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersRoute = PrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerTablesRoute = CustomerTablesRouteImport.update({
  id: '/customer-tables',
  path: '/customer-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const CouriersRoute = CouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const TableTableIdRoute = TableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const PosOrdersRoute = PosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PosRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/couriers': typeof CouriersRoute
  '/customer-tables': typeof CustomerTablesRoute
  '/menus': typeof MenusRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/pos': typeof PosRouteWithChildren
  '/printers': typeof PrintersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/table-history': typeof TableHistoryRoute
  '/tables': typeof TablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/pos/orders': typeof PosOrdersRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/couriers': typeof CouriersRoute
  '/customer-tables': typeof CustomerTablesRoute
  '/menus': typeof MenusRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/printers': typeof PrintersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/table-history': typeof TableHistoryRoute
  '/tables': typeof TablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/pos/orders': typeof PosOrdersRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/pos': typeof PosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/couriers': typeof CouriersRoute
  '/customer-tables': typeof CustomerTablesRoute
  '/menus': typeof MenusRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/pos': typeof PosRouteWithChildren
  '/printers': typeof PrintersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/table-history': typeof TableHistoryRoute
  '/tables': typeof TablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/pos/orders': typeof PosOrdersRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/couriers'
    | '/customer-tables'
    | '/menus'
    | '/orders'
    | '/payment-methods'
    | '/pos'
    | '/printers'
    | '/settings'
    | '/statistics'
    | '/stocks'
    | '/support'
    | '/table-history'
    | '/tables'
    | '/auth/login'
    | '/pos/orders'
    | '/table/$tableId'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/couriers'
    | '/customer-tables'
    | '/menus'
    | '/orders'
    | '/payment-methods'
    | '/printers'
    | '/settings'
    | '/statistics'
    | '/stocks'
    | '/support'
    | '/table-history'
    | '/tables'
    | '/auth/login'
    | '/pos/orders'
    | '/table/$tableId'
    | '/pos'
  id:
    | '__root__'
    | '/'
    | '/couriers'
    | '/customer-tables'
    | '/menus'
    | '/orders'
    | '/payment-methods'
    | '/pos'
    | '/printers'
    | '/settings'
    | '/statistics'
    | '/stocks'
    | '/support'
    | '/table-history'
    | '/tables'
    | '/auth/login'
    | '/pos/orders'
    | '/table/$tableId'
    | '/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouriersRoute: typeof CouriersRoute
  CustomerTablesRoute: typeof CustomerTablesRoute
  MenusRoute: typeof MenusRoute
  OrdersRoute: typeof OrdersRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PosRoute: typeof PosRouteWithChildren
  PrintersRoute: typeof PrintersRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  StocksRoute: typeof StocksRoute
  SupportRoute: typeof SupportRoute
  TableHistoryRoute: typeof TableHistoryRoute
  TablesRoute: typeof TablesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  TableTableIdRoute: typeof TableTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-history': {
      id: '/table-history'
      path: '/table-history'
      fullPath: '/table-history'
      preLoaderRoute: typeof TableHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printers': {
      id: '/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-tables': {
      id: '/customer-tables'
      path: '/customer-tables'
      fullPath: '/customer-tables'
      preLoaderRoute: typeof CustomerTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couriers': {
      id: '/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof CouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/orders': {
      id: '/pos/orders'
      path: '/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof PosOrdersRouteImport
      parentRoute: typeof PosRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PosRouteChildren {
  PosOrdersRoute: typeof PosOrdersRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosOrdersRoute: PosOrdersRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouriersRoute: CouriersRoute,
  CustomerTablesRoute: CustomerTablesRoute,
  MenusRoute: MenusRoute,
  OrdersRoute: OrdersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PosRoute: PosRouteWithChildren,
  PrintersRoute: PrintersRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  StocksRoute: StocksRoute,
  SupportRoute: SupportRoute,
  TableHistoryRoute: TableHistoryRoute,
  TablesRoute: TablesRoute,
  AuthLoginRoute: AuthLoginRoute,
  TableTableIdRoute: TableTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
